{{- if not .Values.s3.internal }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: {{ include "dersplatform.namespace" . }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::269174115166:role/ogret-backend-eks
{{- end }}
