apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - redis.yaml
  - secret.yaml
  - ingress.yaml
  - network-policy.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
    target:
      kind: Service
      name: backend
  - patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
    target:
      kind: Service
      name: frontend
  - patch: |-
      - op: add
        path: /spec/ports/0/nodePort
        value: 30080
    target:
      kind: Service
      name: backend
  - patch: |-
      - op: add
        path: /spec/ports/0/nodePort
        value: 30081
    target:
      kind: Service
      name: frontend
  - patch: |-
      - op: replace
        path: /data/CORS_ORIGINS
        value: "*"
    target:
      kind: ConfigMap
      name: dersplatform-config
  - patch: |-
      - op: add
        path: /data/AWS_S3_ENDPOINT
        value: "https://s3.eu-north-1.amazonaws.com"
    target:
      kind: ConfigMap
      name: dersplatform-config
  - patch: |-
      - op: add
        path: /data/AWS_S3_PUBLIC_URL
        value: "https://s3.eu-north-1.amazonaws.com"
    target:
      kind: ConfigMap
      name: dersplatform-config
  - patch: |-
      - op: add
        path: /data/AWS_S3_REGION
        value: "eu-north-1"
    target:
      kind: ConfigMap
      name: dersplatform-config
  - patch: |-
      - op: replace
        path: /data/DB_URL
        value: "jdbc:postgresql://ogret-test.c7ayqie2c77y.eu-north-1.rds.amazonaws.com:5432/dersplatform"
    target:
      kind: ConfigMap
      name: dersplatform-config
