apiVersion: v1
kind: ConfigMap
metadata:
  name: dersplatform-config
data:
  SPRING_PROFILES_ACTIVE: prod
  DB_URL: jdbc:postgresql://postgres:5432/dersplatform
  DB_USER: dersplatform
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  CORS_ORIGINS: https://ogret.io,https://www.ogret.io
