apiVersion: v1
kind: ConfigMap
metadata:
  name: dersplatform-config
data:
  SPRING_PROFILES_ACTIVE: prod
  DB_URL: jdbc:postgresql://postgres:5432/dersplatform
  DB_USER: dersplatform
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  CORS_ORIGINS: https://ogret.io,https://www.ogret.io
  APP_BASE_URL: http://a84908dcacb2f4bfbb186b3bfbf71f95-2120247910.eu-north-1.elb.amazonaws.com
  AWS_REGION: eu-north-1
  # Temporary SES test sender. Replace with no-reply@your-domain after domain verification.
  MAIL_FROM_EMAIL: furkandogmus9183@gmail.com
