apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      serviceAccountName: backend
      containers:
        - name: backend
          env:
            - name: AWS_S3_ENDPOINT
              value: "https://s3.eu-north-1.amazonaws.com"
            - name: AWS_S3_PUBLIC_URL
              value: "https://ogret-public.s3.eu-north-1.amazonaws.com"
            - name: AWS_S3_REGION
              valueFrom:
                secretKeyRef:
                  name: dersplatform-secret
                  key: AWS_S3_REGION
