apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dersplatform-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: dersplatform-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /ogret/prod/db
        property: password
    - secretKey: JWT_SECRET
      remoteRef:
        key: /ogret/prod/jwt
        property: secret
    - secretKey: AWS_S3_REGION
      remoteRef:
        key: /ogret/prod/aws
        property: region
