apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
  - irsa.yaml
  - external-secrets.yaml
patches:
  - path: backend-patch.yaml
  - path: configmap-patch.yaml
