# kubernetes/backend.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: dersplatform
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dersplatform
spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 269174115166.dkr.ecr.eu-north-1.amazonaws.com/ogret.io/backend:latest
          imagePullPolicy: Never

          ports:
            - name: http
              containerPort: 8080

          envFrom:
            - configMapRef:
                name: dersplatform-config

          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dersplatform-secret
                  key: DB_PASSWORD

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dersplatform-secret
                  key: JWT_SECRET

            - name: AWS_S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: dersplatform-secret
                  key: MINIO_ROOT_USER

            - name: AWS_S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: dersplatform-secret
                  key: MINIO_ROOT_PASSWORD

            - name: AWS_S3_ENDPOINT
              value: "http://minio:9000"

            - name: AWS_S3_PUBLIC_URL
              value: "http://localhost:31605"

          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 750m
              memory: 768Mi