apiVersion: v1
kind: Secret
metadata:
  name: dersplatform-secret
  namespace: dersplatform
type: Opaque
stringData:
  DB_PASSWORD: dersplatform
  JWT_SECRET: local-development-jwt-secret-must-be-at-least-256-bits-long

  POSTGRES_DB: dersplatform
  POSTGRES_USER: dersplatform
  POSTGRES_PASSWORD: dersplatform

  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadminpassword